export const DUMMY_DATA = [
  {
    id: 1,
    title: "Free your buisiness",
    about: "Buisiness solutions",
    time: "01:19",
    video: "/videos/hills.mp4",
    slug: "free-your-business",
    date: "11-04-2025",
  },
  {
    id: 2,
    title: "Endless possibility",
    about: "Posibilities",
    time: "00:50",
    video: "/videos/driving_desert.mp4",
    slug: "endless-possibility",
    date: "28-03-2025",
  },
  {
    id: 3,
    title: "Reach unreachable",
    about: "Sight for new horizons",
    time: "03:31",
    video: "/videos/ocean.mp4",
    slug: "reach-unreachable",
    date: "05-02-2025",
  },
  {
    id: 4,
    title: "Find your clients",
    about: "Easee",
    time: "03:08",
    video: "/videos/vessel.mp4",
    slug: "find-your-clients",
    date: "01-01-2025",
  },
  {
    id: 5,
    title: "Energy to power progress",
    about: "PIO",
    time: "02:24",
    video: "/videos/wind_energy.mp4",
    slug: "energy-to-power-progress",
    date: "01-11-2025",
  },
  {
    id: 6,
    title: "Connect with people",
    about: "Altibox",
    time: "04:11",
    video: "/videos/waves.mp4",
    slug: "connect-with-people",
    date: "14-06-2025",
  },
];
